namespace: "markuman"
description: hetzner dns collection
name: "hetzner_dns"
version: "1.7.0"
readme: "README.md"
authors:
    - "Markus Bergholz <markuman+spambelongstogoogle@gmail.com>"
license:
    - "GPL-3.0-or-later"
tags:
    - hetzner
    - hcloud
    - collection
    - dns
repository: "https://git.osuv.de/m/hetzner_dns"
issues: https://github.com/markuman/hetzner_dns/issues